In [7]:
import pandas as pd
a = pd.read_csv("raw_data.csv")
b = a.copy()
b.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [10]:
b = b.fillna(0)

In [11]:
b["age"] = b["age"].astype("int64")

In [3]:
b

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [13]:
# changing to date time datatype
d = pd.read_csv("globalAirQuality.csv")
d.dtypes

timestamp       object
country         object
city            object
latitude       float64
longitude      float64
pm25           float64
pm10           float64
no2            float64
so2            float64
o3             float64
co             float64
aqi              int64
temperature    float64
humidity       float64
wind_speed     float64
dtype: object

In [14]:
d["timestamp"] = pd.to_datetime(d["timestamp"])
d.dtypes["timestamp"]

dtype('<M8[ns]')

In [15]:
a

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [16]:
a["country"].str.lower()

0        usa
1        usa
2     canada
3        usa
4      spain
5      china
6      india
7        NaN
8        usa
9     mexico
10       usa
Name: country, dtype: object

In [18]:
a["country"].str.upper()

0        USA
1        USA
2     CANADA
3        USA
4      SPAIN
5      CHINA
6      INDIA
7        NaN
8        USA
9     MEXICO
10       USA
Name: country, dtype: object

In [21]:
a["country"].str.capitalize()

0        Usa
1        Usa
2     Canada
3        Usa
4      Spain
5      China
6      India
7        NaN
8        Usa
9     Mexico
10       Usa
Name: country, dtype: object

In [22]:
a["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [23]:
a["country"].str.contains("usa",case = False)

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object