In [7]:
#feature scalling
import pandas as pd
a = pd.read_csv("raw_data.csv")
b = a.copy()

In [8]:
#apply functionc
b["tax"] = b["income"].apply(lambda x : "20%" if x>=60000 else "10%")

In [13]:
#map function
c = {"Male":"M","Female":"F","Unknown":"U"}
b["gender"] = b["gender"].map(c)

In [15]:
#assign function
b.assign(new_income = b["income"]*1.1)

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

In [18]:
#replace function
b["country"] = b["country"].replace("USA","us")

In [19]:
b

    id          name   age country gender   income  tax
0    1      John Doe  29.0      us      M  55000.0  10%
1    1      John Doe  29.0      us      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN      us      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0      us      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0      us    NaN  58000.0  10%