In [1]:
#tranforming data
import pandas as pd
a = pd.read_csv("raw_data.csv")
b = a.copy()

In [2]:
b.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='object')

In [6]:
b.columns = ["Id","Name","age","Country", "Gender", "Income"]

In [12]:
#rename function
b.rename(columns = {"Income":"Salary"})
b.rename(index = {2:"Second"})

        Id          Name   age Country   Gender   Income
0        1      John Doe  29.0     USA     Male  55000.0
1        1      John Doe  29.0     USA     Male  55000.0
Second   2    Jane Smith   NaN  Canada   Female  62000.0
3        3          Alex   NaN     USA  Unknown  47000.0
4        4  Maria Garcia  34.0   Spain   Female      NaN
5        5        Li Wei  27.0   China     Male  51000.0
6        6           NaN  45.0   India   Female  73000.0
7        7    Ahmed Khan  38.0     NaN     Male  68000.0
8        8    Rachel Lee  29.0     USA   Female  62000.0
9        9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10      10   Emily Davis  31.0     USA      NaN  58000.0

In [21]:
#sort values
b.sort_values("Income")
b["age"] = b["age"].fillna(b["age"].median())
b.sort_values(["Income","age"],ascending = False)
b.sort_index()

    Id          Name    age Country   Gender   Income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [23]:
#reset_index function
b.reset_index()
b.reset_index(drop = True)

    Id          Name    age Country   Gender   Income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [28]:
#rank function
b["Rankings"] = b["Income"].rank(ascending = False, method = "dense")

In [29]:
#reorder
b[["Id","Name","age", "Gender", "Income","Country"]]

    Id          Name    age   Gender   Income Country
0    1      John Doe  29.00     Male  55000.0     USA
1    1      John Doe  29.00     Male  55000.0     USA
2    2    Jane Smith  32.75   Female  62000.0  Canada
3    3          Alex  32.75  Unknown  47000.0     USA
4    4  Maria Garcia  34.00   Female      NaN   Spain
5    5        Li Wei  27.00     Male  51000.0   China
6    6           NaN  45.00   Female  73000.0   India
7    7    Ahmed Khan  38.00     Male  68000.0     NaN
8    8    Rachel Lee  29.00   Female  62000.0     USA
9    9   Carlos Ruiz  32.75     Male  45000.0  Mexico
10  10   Emily Davis  31.00      NaN  58000.0     USA

In [30]:
b

    Id          Name    age Country   Gender   Income  Rankings
0    1      John Doe  29.00     USA     Male  55000.0       5.0
1    1      John Doe  29.00     USA     Male  55000.0       5.0
2    2    Jane Smith  32.75  Canada   Female  62000.0       3.0
3    3          Alex  32.75     USA  Unknown  47000.0       7.0
4    4  Maria Garcia  34.00   Spain   Female      NaN       NaN
5    5        Li Wei  27.00   China     Male  51000.0       6.0
6    6           NaN  45.00   India   Female  73000.0       1.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0       2.0
8    8    Rachel Lee  29.00     USA   Female  62000.0       3.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0       8.0
10  10   Emily Davis  31.00     USA      NaN  58000.0       4.0

In [34]:
names = [col for col in b.columns if col!="Id"] +["Id"]
b[names]

            Name    age Country   Gender   Income  Rankings  Id
0       John Doe  29.00     USA     Male  55000.0       5.0   1
1       John Doe  29.00     USA     Male  55000.0       5.0   1
2     Jane Smith  32.75  Canada   Female  62000.0       3.0   2
3           Alex  32.75     USA  Unknown  47000.0       7.0   3
4   Maria Garcia  34.00   Spain   Female      NaN       NaN   4
5         Li Wei  27.00   China     Male  51000.0       6.0   5
6            NaN  45.00   India   Female  73000.0       1.0   6
7     Ahmed Khan  38.00     NaN     Male  68000.0       2.0   7
8     Rachel Lee  29.00     USA   Female  62000.0       3.0   8
9    Carlos Ruiz  32.75  Mexico     Male  45000.0       8.0   9
10   Emily Davis  31.00     USA      NaN  58000.0       4.0  10