In [6]:
import pandas as pd
a = {"name" : ["sumit","kunal","rohan","shubham"],"cgpa":[8.3,8.7,7.4,7.8],"age":[20,23,21,2]}
b = pd.DataFrame(a)
print(b)
print(b.index)
print(b.columns)
b# for visualisation we can only write variable name and it will show

      name  cgpa  age
0    sumit   8.3   20
1    kunal   8.7   23
2    rohan   7.4   21
3  shubham   7.8    2
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'cgpa', 'age'], dtype='object')

      name  cgpa  age
0    sumit   8.3   20
1    kunal   8.7   23
2    rohan   7.4   21
3  shubham   7.8    2

In [8]:
c = pd.DataFrame([["sumit",20],["kunal",23],["ravi",19]],columns = ["name","age"])
c

    name  age
0  sumit   20
1  kunal   23
2   ravi   19

In [9]:
d = [[1,2,3],[4,5,6]]
e = pd.DataFrame(d,columns = ["a","b","c"])
e

   a  b  c
0  1  2  3
1  4  5  6