In [1]:
import pandas as pd
a = pd.read_csv("raw_data.csv")
b = a.copy()

In [5]:
#groupby function
b.groupby("country")
b.groupby("country")["income"].mean()
b.groupby("gender")["income"].max()

gender
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [7]:
#agg function
b.groupby("gender")["income"].agg(["mean","min","max"])

                 mean      min      max
gender
Female   65666.666667  62000.0  73000.0
Male     54800.000000  45000.0  68000.0
Unknown  47000.000000  47000.0  47000.0

In [8]:
b.groupby("gender")["income"].agg(average_income = "mean",minimum_income = "min",maximum_income = "max")

         average_income  minimum_income  maximum_income
gender
Female     65666.666667         62000.0         73000.0
Male       54800.000000         45000.0         68000.0
Unknown    47000.000000         47000.0         47000.0

In [9]:
b.groupby("gender").agg({"income":"mean","age":"max"})

               income   age
gender
Female   65666.666667  45.0
Male     54800.000000  38.0
Unknown  47000.000000   NaN

In [11]:
b.groupby("gender").agg(maximum_salary = ("income","max"),average_age = ("age","mean"))

         maximum_salary  average_age
gender
Female          73000.0        36.00
Male            68000.0        30.75
Unknown         47000.0          NaN

In [3]:
b

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0