In [1]:
import pandas as pd
df = pd.read_csv("IRIS.csv")

In [3]:
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [4]:
df.shape

(150, 5)

In [8]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [10]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [12]:
df[df["petal_length"] > 4.5]

     sepal_length  sepal_width  petal_length  petal_width          species
50            7.0          3.2           4.7          1.4  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor
54            6.5          2.8           4.6          1.5  Iris-versicolor
56            6.3          3.3           4.7          1.6  Iris-versicolor
58            6.6          2.9           4.6          1.3  Iris-versicolor
..            ...          ...           ...          ...              ...
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

[63 rows x 5 columns]

In [13]:
df[df["species"] == "Iris-virginica"]

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
106           4.9          2.5           4.5          1.7  Iris-virginica
107           7.3          2.9           6.3          1.8  Iris-virginica
108           6.7          2.5           5.8          1.8  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
110           6.5          3.2           5.1          2.0  Iris-virginica
111           6.4          2.7           5.3          1.9  Iris-virginica
112           6.8          3.0           5.5          2.1  Iris-virginica
113           5.7          2.5           5.0          2.0  Iris-virginica
114           5.8          2.8           5.1          2.4  Iris-virginica
115           6.4          3.2           5.3          2.3  Iris-virginica
116           6.5          3.0           5.5          1.8  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
119           6.0          2.2           5.0          1.5  Iris-virginica
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [31]:
df[(df["petal_length"] > 4.5) & (df["species"] == "Iris-virginica")]

,sepal_length,sepal_width,petal_length,petal_width,species,petal_ratio
100,6.3,3.3,6.0,2.5,Iris-virginica,2.400000
101,5.8,2.7,5.1,1.9,Iris-virginica,2.684211
102,7.1,3.0,5.9,2.1,Iris-virginica,2.809524
103,6.3,2.9,5.6,1.8,Iris-virginica,3.111111
104,6.5,3.0,5.8,2.2,Iris-virginica,2.636364
105,7.6,3.0,6.6,2.1,Iris-virginica,3.142857
107,7.3,2.9,6.3,1.8,Iris-virginica,3.500000
108,6.7,2.5,5.8,1.8,Iris-virginica,3.222222
109,7.2,3.6,6.1,2.5,Iris-virginica,2.440000
110,6.5,3.2,5.1,2.0,Iris-virginica,2.550000
111,6.4,2.7,5.3,1.9,Iris-virginica,2.789474
112,6.8,3.0,5.5,2.1,Iris-virginica,2.619048
113,5.7,2.5,5.0,2.0,Iris-virginica,2.500000
114,5.8,2.8,5.1,2.4,Iris-virginica,2.125000
115,6.4,3.2,5.3,2.3,Iris-virginica,2.304348
116,6.5,3.0,5.5,1.8,Iris-virginica,3.055556
117,7.7,3.8,6.7,2.2,Iris-virginica,3.045455
118,7.7,2.6,6.9,2.3,Iris-virginica,3.000000
119,6.0,2.2,5.0,1.5,Iris-virginica,3.333333
120,6.9,3.2,5.7,2.3,Iris-virginica,2.478261
121,5.6,2.8,4.9,2.0,Iris-virginica,2.450000
122,7.7,2.8,6.7,2.0,Iris-virginica,3.350000
123,6.3,2.7,4.9,1.8,Iris-virginica,2.722222
124,6.7,3.3,5.7,2.1,Iris-virginica,2.714286
125,7.2,3.2,6.0,1.8,Iris-virginica,3.333333
126,6.2,2.8,4.8,1.8,Iris-virginica,2.666667
127,6.1,3.0,4.9,1.8,Iris-virginica,2.722222
128,6.4,2.8,5.6,2.1,Iris-virginica,2.666667
129,7.2,3.0,5.8,1.6,Iris-virginica,3.625000
130,7.4,2.8,6.1,1.9,Iris-virginica,3.210526
131,7.9,3.8,6.4,2.0,Iris-virginica,3.200000
132,6.4,2.8,5.6,2.2,Iris-virginica,2.545455
133,6.3,2.8,5.1,1.5,Iris-virginica,3.400000
134,6.1,2.6,5.6,1.4,Iris-virginica,4.000000
135,7.7,3.0,6.1,2.3,Iris-virginica,2.652174
136,6.3,3.4,5.6,2.4,Iris-virginica,2.333333
137,6.4,3.1,5.5,1.8,Iris-virginica,3.055556
138,6.0,3.0,4.8,1.8,Iris-virginica,2.666667
139,6.9,3.1,5.4,2.1,Iris-virginica,2.571429
140,6.7,3.1,5.6,2.4,Iris-virginica,2.333333
141,6.9,3.1,5.1,2.3,Iris-virginica,2.217391
142,5.8,2.7,5.1,1.9,Iris-virginica,2.684211
143,6.8,3.2,5.9,2.3,Iris-virginica,2.565217
144,6.7,3.3,5.7,2.5,Iris-virginica,2.280000
145,6.7,3.0,5.2,2.3,Iris-virginica,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,2.833333

In [22]:
df.groupby("species")["sepal_length"].mean()

species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: sepal_length, dtype: float64

In [24]:
df.groupby("species")["petal_width"].max()

species
Iris-setosa        0.6
Iris-versicolor    1.8
Iris-virginica     2.5
Name: petal_width, dtype: float64

In [25]:
df.groupby("species")["sepal_width"].std()

species
Iris-setosa        0.381024
Iris-versicolor    0.313798
Iris-virginica     0.322497
Name: sepal_width, dtype: float64

In [32]:
df.groupby("species").agg({
    "sepal_length" : "mean",
    "petal_width":"max",
    "sepal_width" : "std"
})

                 sepal_length  petal_width  sepal_width
species
Iris-setosa             5.006          0.6     0.381024
Iris-versicolor         5.936          1.8     0.313798
Iris-virginica          6.588          2.5     0.322497

In [28]:
df["petal_ratio"] = df["petal_length"] / df["petal_width"]

In [29]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,petal_ratio
0,5.1,3.5,1.4,0.2,Iris-setosa,7.000000
1,4.9,3.0,1.4,0.2,Iris-setosa,7.000000
2,4.7,3.2,1.3,0.2,Iris-setosa,6.500000
3,4.6,3.1,1.5,0.2,Iris-setosa,7.500000
4,5.0,3.6,1.4,0.2,Iris-setosa,7.000000
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,2.833333